# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 4.1.0-6-g27197b0
_src_path: gh:epics-containers/ioc-template
description: A test instantiation of the ioc-template copier template
git_platform: github.com
github_org: epics-containers
name: ioc-template-example
repo_uri: git@github.com:epics-containers/ioc-template-example.git
rtems: false
